export const copy = {
  navigation: {
    privacyStatus: "Local-only workspace",
    themeToggle: "Toggle color theme",
  },
  welcome: {
    eyebrow: "Private by design",
    title: "Build texture stories, one surface at a time.",
    introduction:
      "Begin with your own mesh or pair a supplied model with one or more displacement maps. Your choices stay on this device.",
    dropTitle: "Drop a 3D model here",
    dropHint: "or choose a binary or ASCII STL file",
    chooseFile: "Choose model file",
    selectedFile: "Local model selected",
    sampleHeading: "Start with a sample",
    sampleSubheading:
      "Choose one model and any textures you want waiting in your project.",
    modelGroup: "Sample models",
    textureGroup: "Sample textures",
    selectionEmpty: "Select a model to begin your sample setup.",
    selectionReady: "Sample setup ready",
    openSample: "Open sample model",
    openLocal: "Open selected model",
    privacy:
      "Your files stay on this device. Nothing is uploaded, and the workspace is discarded when this page closes or reloads.",
    initializationNote:
      "STL viewing, surface painting, texture preview, and source-resolution binary STL export are available.",
    compatibilityTitle: "WebGL 2 is unavailable.",
    compatibilityDetail:
      "Model preview requires a recent browser with hardware acceleration enabled.",
    sectionKicker: "Curated starting points",
    importErrorTitle: "That model could not be opened",
  },
  loading: {
    title: "Preparing your model",
    detail: "Geometry processing stays on this device.",
    cancel: "Cancel import",
    openingViewport: "Opening the private 3D viewport…",
  },
  workspace: {
    back: "Choose another model",
    sourceProtected: "Immutable source",
    sourceDetail: "Preview geometry is rebuilt from a protected source copy.",
    overview: "Mesh overview",
    dimensions: "Dimensions",
    triangles: "Triangles",
    vertices: "Vertices",
    format: "Format",
    units: "Assumed units",
    fileSize: "File size",
    viewportHint: "Drag to orbit · Scroll to zoom · Right-drag to pan",
    paintHint:
      "Drag to paint · Alt-drag to erase · Visible/front-facing surface only",
    tools: "Tools",
    orbitTool: "Orbit",
    paintTool: "Paint selection",
    undo: "Undo stroke",
    redo: "Redo stroke",
    activeLayer: "Active texture layer",
    defaultLayerName: "Texture Layer 1",
    layerNamePrefix: "Texture Layer",
    layerCopySuffix: "Copy",
    layerStack: "Composite order",
    layers: "Texture layers",
    addLayer: "Add layer",
    selectLayer: "Select",
    duplicateLayer: "Duplicate",
    deleteLayer: "Delete active layer",
    moveLayerUp: "Move active layer up",
    moveLayerDown: "Move active layer down",
    showLayer: "Show",
    hideLayer: "Hide",
    layerName: "Layer name",
    blendMode: "Blend mode",
    blendAdd: "Add",
    blendSubtract: "Subtract",
    blendReplace: "Replace",
    coverage: "Coverage",
    radius: "Brush radius",
    hardness: "Hardness",
    strength: "Strength",
    textureHeading: "Height texture",
    textureDetail:
      "Texture height is projected from three axes and blended across curved surfaces.",
    importTexture: "Import height texture",
    importingTexture: "Reading texture...",
    importTextureHint: "PNG, JPEG, or WebP · local only",
    textureImportFailed: "The texture could not be imported.",
    localTexture: "Local texture",
    mappingScale: "Texture scale",
    amplitude: "Amplitude",
    midpoint: "Zero height",
    influence: "Influence",
    invert: "Invert height",
    visible: "Show texture displacement",
    selectedTexture: "Active texture",
    previewBuilding: "Updating texture preview...",
    previewError: "Texture preview unavailable",
    exportKicker: "Printable geometry",
    exportHeading: "Export visible layers",
    exportLayers: "Visible layers",
    exportTriangles: "Source triangles",
    exportEstimate: "Estimated size",
    exportDetail:
      "Exports the current composite at source-mesh resolution. Subdivision is not applied in this release.",
    exportUnits:
      "Binary STL is unitless; coordinate values retain the assumed {units} scale.",
    exportButton: "Export binary STL",
    cancelExport: "Cancel export",
    exportReady: "Ready to export",
    exportPreparing: "Preparing immutable source geometry",
    exportComplete: "STL exported",
    exportCancelled: "Export cancelled",
    exportFailed: "Export could not be completed",
  },
  steps: [
    {
      number: "01",
      title: "Import",
      detail: "Choose a local mesh or supplied sample.",
    },
    {
      number: "02",
      title: "Paint & layer",
      detail: "Target regions with independent, editable masks.",
    },
    {
      number: "03",
      title: "Validate & export",
      detail: "Review geometry before creating a printable mesh.",
    },
  ],
  footer: {
    licenseLabel: "Sample asset licenses",
    browserNote: "Designed for recent desktop browsers with WebGL 2.",
  },
} as const;
